# Generated by Django 4.2.25 on 2025-10-16 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='phonebook.contact'),
        ),
    ]
