name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install django djangorestframework djangorestframework-simplejwt pytest pytest-django structlog colorama django-structlog
          fi

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: tests.settings
          SECRET: insecure-ci-secret
          DEBUG: "0"
          LOG_LEVEL: "WARNING"
        run: |
          pytest -q
